version: "3.8"
services:
  web:
    image: "${IMAGE:-registry.gitlab.com/your-group/your-project:latest}"
    restart: always
    env_file: .env.production
    ports:
      - "127.0.0.1:5000:5000" # bind to localhost so Nginx on host can reverse-proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:5000/_next/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
